name: CI-Build

on:
  push:
  pull_request:
  schedule:
    - cron:  '21 21 * * *'
  workflow_dispatch:

jobs:
  build:
    uses: axonivy-market/github-workflows/.github/workflows/dev.yml@v3
    with:
      mvnArgs: '-Divy.script.validation.skip=true'
